### ISSUE TITLE
Incorrect dependency version declared in 

### ISSUE THREAD

**Issue by egor-n** [muxinc/mux-stats-sdk-media3#18]
In `data-media3` 0.7.0 release, there's an incorrect dependency version declared in the `pom.xml` (line 31) for `data-media3-custom` - https://muxinc.jfrog.io/artifactory/default-maven-release-local/com/mux/stats/sdk/muxstats/data-media3/0.7.0/data-media3-0.7.0.pom

<img width="1167" alt="image" src="https://github.com/muxinc/mux-stats-sdk-media3/assets/378493/352a68c6-f7ce-430b-9c69-aa40054110c1">

**Comment by daytime-em** [comment]
Thank you for your report. I think I've found the issue and we expect to have a fix out today.

**Comment by daytime-em** [comment]
This should be fixed in v0.7.1, which is now available on our maven. Thanks again for your report!
