### ISSUE TITLE
Update Mux Stats to use Media3 1.1.1

### ISSUE THREAD

**Issue by wajahatkarim3** [muxinc/mux-stats-sdk-media3#31]
Currently, Mux Stats v0.7.4 is using Media3 1.1.0 internally. Can you please update this to use 1.1.1 as that's more stable version.

**Comment by daytime-em** [comment]
Thank you for this report

You should be able to safely update your app's media3 dependency to `1.1.1` without causing any build issues. Gradle's version matching will permit this, and prefer the version you declare.

Please refer to the attached screenshot, with a sample of this in action:
<img width="1226" alt="Screenshot 2023-08-31 at 12 52 09 PM" src="https://github.com/muxinc/mux-stats-sdk-media3/assets/319221/c2d63d84-e7b9-461c-a80f-21c79732791f">

If you are experiencing build or runtime issues, please let me know and I can help.

Thanks again!

**Comment by daytime-em** [comment]
Closing, per my above comment. Please see the attached screenshot for a configuration that will package media3 1.1.1 in your final application.

Feel free to reopen if you are experiencing any build issues :)
