### ISSUE TITLE
Miss 'seeked' or 'playing'  event

### ISSUE THREAD

**Issue by WeiLiuSH** [muxinc/mux-stats-sdk-media3#39]
<img width="1216" alt="image" src="https://github.com/muxinc/mux-stats-sdk-media3/assets/141914274/2bc94fb5-cac4-4d52-b846-81923a866b06">
<img width="1205" alt="image" src="https://github.com/muxinc/mux-stats-sdk-media3/assets/141914274/0da3a342-ea89-41c4-bcdd-d242187444d0">
<img width="1196" alt="image" src="https://github.com/muxinc/mux-stats-sdk-media3/assets/141914274/de60d374-29f7-4360-b22d-798ed256869a">

It looks like miss 'seeked' or 'playing' after 'seeking' event.
**This problem can not be reproduced 100%!!!** 
Do you have any ideas or tips which could help us to identify the issue?
Thanks.

mux sdk: v1.0.0

**Comment by daytime-em** [comment]
Hey, sorry to hear you're still having trouble.

Something I noticed is that both of the cases seem to involve seeking during an ad. I'd like to ask you for some information that may be too sensitive for GitHub.

Would you mind filling out a support request on our [website](http://mux.com/support)? I've let them know to expect you. Thank you!

**Comment by daytime-em** [comment]
A fix for this is now available in v1.0.1 of the SDK. Please reach out if you see any more issues!
