### ISSUE TITLE
How to use mux to support our own player on Android？

### ISSUE THREAD

**Issue by TravisLiao** [muxinc/mux-stats-sdk-media3#59]
Hello, the player we use is self-developed internally and is not listed in the mux supported player list.
Is there any way to implement it？
Thanks!

**Comment by dylanjha** [comment]
Hi @TravisLiao, yes! We have guides for [Creating a custom integration](https://docs.mux.com/guides/build-a-custom-data-integration) with Mux Data

[Here's the one for Android](https://docs.mux.com/guides/data-custom-java-integration)

You basically install the core SDK (which is not player-specific) and integrate your player code to dispatch events and data to the core SDK. Please reach out to support so we can assist!

**Comment by TravisLiao** [comment]
Thanks! @dylanjha
