### ISSUE TITLE
Missing functionality for `clearing` video data without releasing

### ISSUE THREAD

**Issue by cole-smith** [muxinc/mux-stats-sdk-media3#84]
Our app's architecture allows for an ExoPlayer to outlive the scope of a single video. For example, one ExoPlayer might go through the following state changes:
```
exoPlayer.prepare()
[ start View of some video ]
exoPlayer.setMediaItem([mediaId = 1])
[ play media for 10 seconds ]
[ user clears video; end playback]
exoPlayer.removeMediaItem([mediaId = 1])
[ wait some time ]
[ start new View of same video ]
exoPlayer.setMediaItem([mediaId = 1])
```
Currently, I don't believe that the Mux stats SDK can properly handle this behavior. If I do nothing, then the first "view" (from the user's perspective) and second "view" are combined into a single View in the MUX dashboard, with a massive pause in between, which is not reflective of the user experience (where there was two distinct playback sessions that occurred). I can call `videoChange(CustomerVideoData())` after `exoPlayer.removeMediaItem`, but I'm not sure if that does what I would expect.

Ideally, I'd be able to call something like `muxStats.clearVideo()` after `exoPlayer.removeMediaItem`, which would prevent the Mux stats from being reported during the exoPlayer's downtime. 

In a similar vein, we might also use this ExoPlayer instance for non-MUX playback, in which case I'd like to avoid reporting data during that session. From an API standpoint, being able to disable/enable stat collection without calling `muxStats.release()` would be ideal. 

I'm aware that I could `release()` the Mux Stats after calling `removeMediaItem`, but that poses a couple of problems. Firstly, it would not be ideal to repeatedly recreate a `MuxStats` instance for the same ExoPlayer instance, and secondly, your documentation states that the `MuxStats` instance needs to be created prior to calling `prepare()` on the Player. Therefore, releasing and recreating an instance during the same `ExoPlayer` life-cycle would violate those expectations.

**Comment by daytime-em** [comment]
@cole-smith In v1.5.0 of the SDK, you should be able to find `disable` and `enable()` methods on `MuxStatsSdkMedia3`. 

When disabled, the SDK should end the current view and go dormant until `enable()` is called again. `enable()` will start a new view, and apply the `CustomerData` you provide to it.

Please feel free to reach out if you have any problems!
