### ISSUE TITLE
Device category is Wrong

### ISSUE THREAD

**Issue by AkhilMohan-R** [muxinc/mux-stats-sdk-media3#94]
The device category that we get on the mux dashboard is wrong and i didn't find any option to update it manually from the developer side.

**Comment by daytime-em** [comment]
Hi!

Thanks for your report. We'll look into this and try to provide a solution.

Are you seeing the wrong category for _every_ device, or are there specific devices that are not being detected correctly?

**Comment by AkhilMohan-R** [comment]
Yes the issue is happening for some of the STBs, the device category is
getting as phone. Is there any option to add the category by ourself

**Comment by daytime-em** [comment]
I've forwarded your request to our Product team.

In the mean time, we can also try to fix the device detection. I'll let you know how it goes!

**Comment by daytime-em** [comment]
@AkhilMohan-R 

We actually do support overriding the device category. You can customize it like this:

```kotlin
val customerData = CustomerData()
val viewerData = CustomerViewerData()
customerData.customerViewerData = viewerData
viewerData.muxDeviceCategory = "tv"

muxStats.updateCustomerData(customerData)
```

**Comment by daytime-em** [comment]
Since I haven't heard back, I'll close this.

If you have any additional issues, please reopen!
